apiVersion: v1
kind: Service
metadata:
  name: mnist-service
spec:
  type: ClusterIP  # Use NodePort or LoadBalancer if external access is required
  ports:
  - port: 9201
    targetPort: 9201
    protocol: TCP
  selector:
    app: mnist
