apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-inference
spec:
  replicas: 2  # You can define the number of replicas based on your load requirements
  selector:
    matchLabels:
      app: mnist
  template:
    metadata:
      labels:
        app: mnist
    spec:
      containers:
      - name: mnist-container
        image: mnist-flask-app:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
